# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JumpscareSim(object):
    def setupUi(self, JumpscareSim):
        JumpscareSim.setObjectName("JumpscareSim")
        JumpscareSim.resize(784, 431)
        self.centralwidget = QtWidgets.QWidget(JumpscareSim)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 20, 771, 421))
        self.widget.setToolTip("")
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(80, 50, 141, 141))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"      background-color: rgb(0, 0, 0);\n"
"      border-radius: 20px;\n"
"      image: url(:/assets/chica_icon.png);\n"
"}\n"
"QPushButton:hover {\n"
"      background-color: rgb(0, 0, 0);\n"
"      border: 2px solid #ffffff;\n"
"}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 40, 151, 151))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"      background-color: rgb(0, 0, 0);\n"
"      border-radius: 20px;\n"
"      image: url(:/assets/Monster_rat_icon.png);\n"
"}\n"
"QPushButton:hover {\n"
"      background-color: rgb(0, 0, 0);\n"
"      border: 2px solid #ffffff;\n"
"}\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(530, 50, 131, 141))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"      background-color: rgb(0, 0, 0);\n"
"      border-radius: 20px;\n"
"      image: url(:/assets/Mangle_icon.png);\n"
"}\n"
"QPushButton:hover {\n"
"      background-color: rgb(0, 0, 0);\n"
"      border: 2px solid #ffffff;\n"
"}\n"
"")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 761, 391))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        JumpscareSim.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(JumpscareSim)
        self.statusbar.setObjectName("statusbar")
        JumpscareSim.setStatusBar(self.statusbar)

        self.retranslateUi(JumpscareSim)
        QtCore.QMetaObject.connectSlotsByName(JumpscareSim)

    def retranslateUi(self, JumpscareSim):
        _translate = QtCore.QCoreApplication.translate
        JumpscareSim.setWindowTitle(_translate("JumpscareSim", "MainWindow"))
import resources_rc
